import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { ArrowLeft, Search, UserPlus, Users } from "lucide-react";
const labels:Record<string,string>={active:"Aktif",inactive:"Tidak aktif",suspended:"Digantung",deceased:"Meninggal dunia"};
export default async function MembersPage({searchParams}:{searchParams:Promise<{q?:string;area?:string;category?:string;status?:string}>}){
 const f=await searchParams,s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)redirect("/login");
 let query=s.from("members").select("id,member_no,full_name,identification_no,phone,status,areas(name),member_categories(name)").order("created_at",{ascending:false}).limit(100);
 const term=(f.q||"").replaceAll(",","");if(term)query=query.or(`full_name.ilike.%${term}%,member_no.ilike.%${term}%,identification_no.ilike.%${term}%`);if(f.area)query=query.eq("area_id",f.area);if(f.category)query=query.eq("category_id",f.category);if(f.status)query=query.eq("status",f.status);
 const [{data:members,error},{data:areas},{data:categories}]=await Promise.all([query,s.from("areas").select("id,name").eq("active",true).order("name"),s.from("member_categories").select("id,name").eq("active",true).order("name")]);
 return <main className="module-page"><div className="module-wrap"><Link className="back" href="/"><ArrowLeft size={17}/> Dashboard</Link><header className="module-head"><div><p className="eyebrow">MODUL PENGURUSAN AHLI</p><h1>Direktori Ahli</h1><span>Daftar, cari dan kemas kini rekod ahli kariah.</span></div><Link className="btn-inline" href="/members/new"><UserPlus size={18}/> Daftar Ahli</Link></header><form className="filter-card"><div className="search-field"><Search size={18}/><input name="q" defaultValue={f.q||""} placeholder="Cari nama, nombor ahli atau kad pengenalan"/></div><select name="area" defaultValue={f.area||""}><option value="">Semua kawasan</option>{areas?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="category" defaultValue={f.category||""}><option value="">Semua kategori</option>{categories?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="status" defaultValue={f.status||""}><option value="">Semua status</option><option value="active">Aktif</option><option value="inactive">Tidak aktif</option><option value="suspended">Digantung</option><option value="deceased">Meninggal dunia</option></select><button className="btn-filter">Cari</button></form><section className="card member-list"><div className="list-summary"><div><Users size={18}/><strong>{members?.length||0}</strong> rekod dipaparkan</div><small>Maksimum 100 rekod bagi setiap carian</small></div>{error?<div className="error">{error.message}</div>:members?.length?<div className="table-scroll"><table className="table"><thead><tr><th>No. Ahli</th><th>Nama</th><th>Kawasan</th><th>Kategori</th><th>Telefon</th><th>Status</th><th></th></tr></thead><tbody>{members.map((m:any)=><tr key={m.id}><td><strong>{m.member_no}</strong></td><td>{m.full_name}<br/><small>{m.identification_no||"—"}</small></td><td>{m.areas?.name||"—"}</td><td>{m.member_categories?.name||"—"}</td><td>{m.phone||"—"}</td><td><span className={`pill status-${m.status}`}>{labels[m.status]}</span></td><td><Link className="table-link" href={`/members/${m.id}`}>Lihat / Edit</Link></td></tr>)}</tbody></table></div>:<div className="empty">Belum ada ahli atau tiada rekod sepadan dengan carian.</div>}</section></div></main>
}
